force-app/main/default/objects/Interaction__x/Interaction__x.object-meta.xml
<CustomObject>
    <description>Interaction</description>
    <externalDataSource>Interactions</externalDataSource>
    <externalName>Interaction</externalName>
    <label>Interaction</label>
    <pluralLabel>Interaction</pluralLabel>
</CustomObject>

force-app/main/default/objects/Interaction__x/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account</description>
    <externalDeveloperName>Account</externalDeveloperName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interaction__x/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <description>Content</description>
    <externalDeveloperName>Content</externalDeveloperName>
    <label>Content</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Interaction__x/fields/HouseholdMember__c.field-meta.xml
<CustomField>
    <fullName>HouseholdMember__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>HouseholdMember</description>
    <externalDeveloperName>HouseholdMember</externalDeveloperName>
    <label>HouseholdMember</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>HouseholdMember</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interaction__x/fields/InteractionDate__c.field-meta.xml
<CustomField>
    <fullName>InteractionDate__c</fullName>
    <description>InteractionDate</description>
    <externalDeveloperName>InteractionDate</externalDeveloperName>
    <label>InteractionDate</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Interaction__x/fields/ModifiedDate__c.field-meta.xml
<CustomField>
    <fullName>ModifiedDate__c</fullName>
    <description>ModifiedDate</description>
    <externalDeveloperName>ModifiedDate</externalDeveloperName>
    <label>ModifiedDate</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Interaction__x/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity</description>
    <externalDeveloperName>Opportunity</externalDeveloperName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interaction__x/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <description>Subject</description>
    <externalDeveloperName>Subject</externalDeveloperName>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/InteractionsListController.cls
public class InteractionsListController {
    // ApexPages.StandardSetController must be instantiated
    // for standard list controllers
    // 
    List<String> AccountIds = new List<String>();
    List<String> ExternalIds = new List<String>();
    String AccountName = '';
    
    public String getAccountName() {
        Account a = [select Name from Account where Id = :AccountIds limit 1];
        return a.Name;
    }
    
    public ApexPages.StandardSetController setCon {
        get {
            if(setCon == null) {
                String iQuery = '';
                if (AccountIds.size() > 0) {
                	iQuery = 'SELECT Id, ModifiedDate__c, InteractionDate__c, Type__c, Subject__c, Content__c, ' +
                        	 'DisplayUrl, Owner__c, Name__c, VersionData__c, Account__r.Name, '+
                        	 'Opportunity__r.Name, HouseholdMember__r.Name ' +
                        	 'FROM Interaction__x ' +
                        	 'WHERE Account__c = :AccountIds ';
                    if (ExternalIds.size() > 0 ) {
                        iQuery += 'AND ExternalId = :ExternalIds';
                    }
                }
                
                System.Debug('Sriram Query Interactions: ' + iQuery);
                List<Interaction__x> li = Database.query(iQuery);
                System.Debug('Sriram List Interactions: ' + li);

                setCon = new ApexPages.StandardSetController(li);
            }
            return setCon;
        }
        set;
    }

    // Initialize setCon and return a list of records
    public List<Interaction__x> getInteractions() {
        try {
	        AccountIds = ApexPages.currentPage().getParameters().get('AccountIds').split(',');
        } catch(Exception e) {
            AccountIds = new List<String>();
        }
        
        System.Debug('Sriram AccountIds: ' + AccountIds);

        try {
       		ExternalIds = ApexPages.currentPage().getParameters().get('ExternalIds').split(',');
        } catch(Exception e) {
            ExternalIds = new List<String>();
        }

        System.Debug('Sriram ExternalIds: ' + ExternalIds);

        return (List<Interaction__x>) setCon.getRecords();
    }
}